Самостоятельное задание:
Необходимо выбрать одну из automl моделей и обучить задачу регрессии.

Напомню, что за данные

### Данные

Каждая строка — заказ доставки еды за 2025 год.
В данных есть характеристики заказа, курьера, ресторана, погоды и дорожной ситуации.

**Основные признаки:**

* `order_datetime` — время заказа (с января по октябрь 2025).
* `distance_km`, `items_count`, `subtotal`, `prep_time_min` — особенности заказа.
* `courier_experience_yrs`, `courier_rating`, `restaurant_rating`.
* `weather`, `traffic`, `area`, `temperature_c`, `holiday`, `surge_coef`.
* **`delivery_time_min`** — целевая переменная (время доставки в минутах).

In [17]:
import pandas as pd

url = "https://raw.githubusercontent.com/totiela/stepik_simulator_ds/main/lessons/lesson_4_1/4_1_homework_dataset.csv"
df  = pd.read_csv(url)

df.sample(3)

,order_id,order_datetime,distance_km,items_count,subtotal,prep_time_min,courier_experience_yrs,courier_rating,restaurant_rating,weather,traffic,is_rain,is_snow,temperature_c,weekday,hour,surge_coef,area,holiday,delivery_time_min
38455,O038456,2025-04-08 09:50:24.292526150,2.36,4,45.87,23.45,6.36,4.69,4.48,wind,low,0,0,18.1,1,9,1.00,South,0,39.66
42177,O042178,2025-04-17 11:53:02.376325767,3.26,3,35.13,14.26,1.92,4.59,4.46,rain,medium,1,0,11.2,3,11,1.05,North,0,52.51
74134,O074135,2025-07-07 18:57:11.555577094,0.84,1,19.07,14.50,0.52,4.52,4.44,cloudy,medium,0,0,7.0,0,18,1.20,West,0,35.22

Разделим данные на train и test (out-of-time). train - выборка для обучения, oot - исключительно для финальной валидации.

In [18]:
train_df = df[df['order_datetime'] < '2025-09-01']
oot_df = df[df['order_datetime'] >= '2025-09-01']

len(train_df), len(oot_df)

(95946, 24054)

In [19]:
target = 'delivery_time_min'
cols_to_drop = ['order_id', 'order_datetime']

Далее обучите любую из automl моделей

https://lightautoml.readthedocs.io/en/v.0.4.0/pages/tutorials/Tutorial_1_basics.html

In [20]:
# чтобы в colab установить AutoGluon - расскоментируй скрип
!pip install autogluon -q --extra-index-url https://download.pytorch.org/whl/cpu

In [21]:
# чтобы в colab установить LightAutoML - расскоментируй скрипт ниже а затем перезапусти ядро.
# !pip install numpy==1.26.4
# !pip install -U 'lightautoml[all]'

In [22]:
# ваш код

После обучения посмотрите метрику MAE на train и oot выборках -> внесите ваше значение метрики на OOT в степик.

In [23]:
from sklearn.metrics import mean_absolute_error

# Ваш код

train_data = train_df.drop(cols_to_drop, axis=1)
oot_data = oot_df.drop(cols_to_drop, axis=1)

In [24]:
from autogluon.tabular import TabularDataset, TabularPredictor

In [25]:
time_limit = 180  # время в секундах
metric = 'mae'  # валдиационная метрика
predictor = TabularPredictor(
    target,
    eval_metric=metric).fit(train_data,
                            time_limit=time_limit,
                            presets='high_quality' # самый простой режим
                            )

No path specified. Models will be saved in: "AutogluonModels/ag-20261025_163312"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.6.3
Python Version:     3.13.16
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.11.0+cu130
CUDA Version:       13.0
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       10.82 GB / 12.67 GB (85.4%)
Disk Space Avail:   68.46 GB / 112.64 GB (60.8%)
===================================================
Presets specified: ['high_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
Note: `save_bag_folds=False`! This will greatly reduce peak disk usage during fit (by ~8x), but runs the risk of an out-of-memory error during model refit if memory is small relative to the data size.
	You can avoid this risk by setting `save_bag_folds=True`.
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 45s of the 180s of remaining time (25%).
DyStack: Disabling memory safe fit mode in DyStack because GPUs were detected and num_gpus='auto' (GPUs cannot be used in memory safe fit mode). If you want to use memory safe fit mode, manually set `num_gpus=0`.
Running DyStack sub-fit ...
Beginning AutoGluon training ... Time limit = 45s
AutoGluon will save models to "/content/AutogluonModels/ag-20261025_163312/ds_sub_fit/sub_fit_ho"
Train Data Rows:    85285
Train Data Columns: 17
Label Column:       delivery_time_min
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11098.47 MB
	Train Data (Original)  Memory Usage: 22.25 MB (0.2% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 8 | ['distance_km', 'subtotal', 'prep_time_min', 'courier_experience_yrs', 'courier_rating', ...]
		('int', [])    : 6 | ['items_count', 'is_rain', 'is_snow', 'weekday', 'hour', ...]
		('object', []) : 3 | ['weather', 'traffic', 'area']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['weather', 'traffic', 'area']
		('float', [])     : 8 | ['distance_km', 'subtotal', 'prep_time_min', 'courier_experience_yrs', 'courier_rating', ...]
		('int', [])       : 3 | ['items_count', 'weekday', 'hour']
		('int', ['bool']) : 3 | ['is_rain', 'is_snow', 'holiday']
	0.3s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 7.65 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.39s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 29.73s of the 44.60s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=1.07%)
	-2.9985	 = Validation score   (-mean_absolute_error)
	34.85s	 = Training   runtime
	2.68s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 44.61s of the -5.71s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.1 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	-2.9985	 = Validation score   (-mean_absolute_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: WeightedEnsemble_L3 ... Training model for up to 44.61s of the -5.88s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.1 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	-2.9985	 = Validation score   (-mean_absolute_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 50.93s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 3984.0 rows/s (10661 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.1/9.1 GB
	2.39s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	0.01s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	0.01s	 = Training   runtime
Updated best model to "LightGBMXT_BAG_L1_FULL" (Previously "WeightedEnsemble_L2"). AutoGluon will default to using "LightGBMXT_BAG_L1_FULL" for predict() and predict_proba().
Refit complete, total runtime = 2.46s ... Best model: "LightGBMXT_BAG_L1_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20261025_163312/ds_sub_fit/sub_fit_ho")
Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                      model  score_holdout  score_val          eval_metric  pred_time_test pred_time_val  fit_time  pred_time_test_marginal pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0    LightGBMXT_BAG_L1_FULL      -2.944968  -2.998484  mean_absolute_error        0.188956          None  2.389404                 0.188956                   None           2.389404            1       True          1
1  WeightedEnsemble_L3_FULL      -2.944968  -2.998484  mean_absolute_error        0.190702          None  2.396788                 0.001745                   None           0.007384            3       True          3
2  WeightedEnsemble_L2_FULL      -2.944968  -2.998484  mean_absolute_error        0.190912          None  2.401176                 0.001955                   None           0.011772            2       True          2
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	55s	 = DyStack   runtime |	125s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 125s
AutoGluon will save models to "/content/AutogluonModels/ag-20261025_163312"
Train Data Rows:    95946
Train Data Columns: 17
Label Column:       delivery_time_min
Problem Type:       regression
Preprocessing data...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10007.17 MB
	Train Data (Original)  Memory Usage: 25.03 MB (0.3% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 8 | ['distance_km', 'subtotal', 'prep_time_min', 'courier_experience_yrs', 'courier_rating', ...]
		('int', [])    : 6 | ['items_count', 'is_rain', 'is_snow', 'weekday', 'hour', ...]
		('object', []) : 3 | ['weather', 'traffic', 'area']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 3 | ['weather', 'traffic', 'area']
		('float', [])     : 8 | ['distance_km', 'subtotal', 'prep_time_min', 'courier_experience_yrs', 'courier_rating', ...]
		('int', [])       : 3 | ['items_count', 'weekday', 'hour']
		('int', ['bool']) : 3 | ['is_rain', 'is_snow', 'holiday']
	0.4s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 8.60 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.46s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 82.77s of the 124.17s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=1.25%)
	-2.94	 = Validation score   (-mean_absolute_error)
	90.81s	 = Training   runtime
	15.48s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 124.20s of the 28.41s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.4 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	-2.94	 = Validation score   (-mean_absolute_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 28.38s of the 28.34s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=1.33%)
	-2.9611	 = Validation score   (-mean_absolute_error)
	45.24s	 = Training   runtime
	4.45s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 124.20s of the -21.31s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.1 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.773, 'LightGBMXT_BAG_L2': 0.227}
	-2.9379	 = Validation score   (-mean_absolute_error)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 146.12s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 601.6 rows/s (11994 batch size)
Automatically performing refit_full as a post-fit operation (due to `.fit(..., refit_full=True)`
Refitting models via `predictor.refit_full` using all of the data (combined train and validation)...
	Models trained in this way will have the suffix "_FULL" and have NaN validation score.
	This process is not bound by time_limit, but should take less time than the original `predictor.fit` call.
	To learn more, refer to the `.refit_full` method docstring which explains how "_FULL" models differ from normal models.
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1_FULL ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.1/9.1 GB
	7.89s	 = Training   runtime
Fitting model: WeightedEnsemble_L2_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
	0.01s	 = Training   runtime
Fitting 1 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2_FULL ...
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.1/9.1 GB
	3.87s	 = Training   runtime
Fitting model: WeightedEnsemble_L3_FULL | Skipping fit via cloning parent ...
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.773, 'LightGBMXT_BAG_L2': 0.227}
	0.1s	 = Training   runtime
Updated best model to "WeightedEnsemble_L3_FULL" (Previously "WeightedEnsemble_L3"). AutoGluon will default to using "WeightedEnsemble_L3_FULL" for predict() and predict_proba().
Refit complete, total runtime = 12.09s ... Best model: "WeightedEnsemble_L3_FULL"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20261025_163312")

In [26]:
predictor.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,WeightedEnsemble_L3,-2.937941,mean_absolute_error,19.940503,136.151660,0.003841,0.099529,3,False,4
1,LightGBMXT_BAG_L1,-2.940026,mean_absolute_error,15.482754,90.809442,15.482754,90.809442,1,False,1
2,WeightedEnsemble_L2,-2.940026,mean_absolute_error,15.485146,90.816978,0.002392,0.007537,2,False,2
3,LightGBMXT_BAG_L2,-2.961147,mean_absolute_error,19.936662,136.052131,4.453908,45.242689,2,False,3
4,WeightedEnsemble_L3_FULL,NaN,mean_absolute_error,NaN,11.860335,NaN,0.099529,3,True,8
5,WeightedEnsemble_L2_FULL,NaN,mean_absolute_error,NaN,7.900008,NaN,0.007537,2,True,6
6,LightGBMXT_BAG_L2_FULL,NaN,mean_absolute_error,NaN,11.760806,NaN,3.868335,2,True,7
7,LightGBMXT_BAG_L1_FULL,NaN,mean_absolute_error,NaN,7.892471,NaN,7.892471,1,True,5

In [28]:
train_preds = predictor.predict(train_data)
oot_preds = predictor.predict(oot_data)

In [39]:
print(f'train score: {mean_absolute_error(train_data[target].values, train_preds.values)}')
print(f'oot score: {mean_absolute_error(oot_data[target].values, oot_preds.values)}')

train score: 2.7740219948954907
oot score: 2.9568307703820174